version: '3.8' # Specify the version of Docker Compose

services:
  # PostgreSQL service definition
  postgres:
    image: postgres:14 # Use the PostgreSQL 14 image
    environment: # Environment variables for PostgreSQL
      POSTGRES_USER: postgres # Set the default user
      POSTGRES_PASSWORD: password # Set the default password
      POSTGRES_DB: secure_live_chat # Set the default database
    ports:
      - "5432:5432" # Map PostgreSQL port 5432 to localhost 5432
    volumes:
      - pgdata:/var/lib/postgresql/data # Persist PostgreSQL data in a Docker volume

  # Redis service definition
  redis:
    image: redis:7 # Use the Redis 7 image
    ports:
      - "6379:6379" # Map Redis port 6379 to localhost 6379

  # Application service definition
  app:
    build: . # Build from the current directory (Dockerfile)
    environment: # Environment variables for the application
      POSTGRES_HOST: postgres # PostgreSQL service hostname
      POSTGRES_PORT: 5432 # PostgreSQL port
      POSTGRES_USER: postgres # PostgreSQL user
      POSTGRES_PASSWORD: password # PostgreSQL password
      POSTGRES_DB: secure_live_chat # PostgreSQL database name
      REDIS_HOST: redis # Redis service hostname
      REDIS_PORT: 6379 # Redis port
      NODE_ENV: development # Environment mode (development)
    depends_on: # Ensure these services are started before the app
      - postgres
      - redis
    ports:
      - "3000:3000" # Map the app port 3000 to localhost 3000

# Define a named volume to persist PostgreSQL data
volumes:
  pgdata:
