version: '3.8' # Specify the version of Docker Compose

services:
  postgres:
    image: postgres:14 # Use the PostgreSQL 14 image
    environment:
      POSTGRES_USER: postgres # Set the default user
      POSTGRES_PASSWORD: password # Set the default password
      POSTGRES_DB: secure_live_chat # Set the default database
    ports:
      - "5432:5432" # Map PostgreSQL port to localhost
    volumes:
      - pgdata:/var/lib/postgresql/data # Persist PostgreSQL data
  redis:
    image: redis:7 # Use the Redis 7 image
    ports:
      - "6379:6379" # Map Redis port to localhost

  app:
    build: . # Build from the current directory (Dockerfile)
    environment:
      POSTGRES_HOST: postgres # PostgreSQL service hostname
      POSTGRES_PORT: 5432 # PostgreSQL port
      POSTGRES_USER: postgres # PostgreSQL user
      POSTGRES_PASSWORD: password # PostgreSQL password
      POSTGRES_DB: secure_live_chat # PostgreSQL database name
      REDIS_HOST: redis # Redis service hostname
      REDIS_PORT: 6379 # Redis port
    depends_on: # Ensure these services are started before the app
      - postgres
      - redis
    ports:
      - "3000:3000" # Map the app port to localhost

volumes:
  pgdata: # Named volume to persist PostgreSQL data
